In [36]:
# Importando Librerias
import pandas as pd

In [37]:
#Variables
FILE = "C:\Data\FuelSalesDataSample.csv" # variable con el path del archivo
FILE_OUT = "outData.csv"

In [38]:
data = pd.read_csv(FILE)

In [39]:
data

,Date,Weekday,Hour,SiteID,SiteName,Grade,Pump,ServiceType,VolumeSold,PaymentType,UnitPrice,TotalSale
0,01/01/2017,7,0,6601,Falls Church,REGULAR,1,FULL,7.40,CASH,2.78,20.57
1,01/01/2017,7,0,6601,Falls Church,REGULAR,3,FULL,11.03,CASH,2.78,30.66
2,01/01/2017,7,0,6601,Falls Church,REGULAR,5,FULL,11.70,CREDIT CARD,2.78,32.53
3,01/01/2017,7,0,6601,Falls Church,REGULAR,7,SELF,15.68,CASH,2.73,42.81
4,01/01/2017,7,0,6601,Falls Church,DIESEL,7,SELF,4.51,CREDIT CARD,2.87,12.94
...,...,...,...,...,...,...,...,...,...,...,...,...
89537,01/15/2017,7,15,6653,Brussels Avenue,REGULAR,5,SELF,9.42,CREDIT CUSTOMER,2.75,25.91
89538,01/15/2017,7,16,6653,Brussels Avenue,REGULAR,5,SELF,10.12,CREDIT CARD,2.75,27.83
89539,01/15/2017,7,17,6653,Brussels Avenue,REGULAR,5,SELF,8.89,CREDIT CARD,2.75,24.45
89540,01/15/2017,7,18,6653,Brussels Avenue,REGULAR,5,SELF,7.21,CREDIT CARD,2.75,19.83
89541,01/15/2017,7,19,6653,Brussels Avenue,REGULAR,5,SELF,5.78,CREDIT CARD,2.75,15.90

In [40]:
data_regular = data[data.Grade.eq("REGULAR")]

In [41]:
data_regular = data_regular.groupby(['SiteName']).mean()

In [42]:
data_regular

,Weekday,Hour,SiteID,Pump,VolumeSold,UnitPrice,TotalSale
SiteName,,,,,,,
American Plaza,4.091497,13.088725,6635.0,2.505545,15.303059,2.745370,42.036959
Brasilia Park,3.997691,13.465358,6645.0,2.408776,15.618684,2.735982,42.744700
Broadway Place,4.035874,13.034978,6606.0,2.512108,7.590018,2.784960,21.142897
Brussels Avenue,3.747396,12.455729,6653.0,3.518229,11.046003,2.773763,30.503750
Cranberry Bridge,4.200000,13.000000,6605.0,1.500000,37.330956,2.730000,101.922244
Crown Hill,4.058415,13.294633,6613.0,7.228916,13.352366,2.750219,36.627430
Diamond Road,4.073269,13.852657,6616.0,2.851047,17.138889,2.781280,47.755660
Falls Church,4.270852,12.720777,6601.0,6.249028,16.981007,2.765468,46.989620
Fashion Square,4.182985,13.555133,6607.0,4.486692,17.255471,2.795076,48.186050
Federal Triangle,4.041587,13.243308,6611.0,4.447897,16.552854,2.774422,45.870569
Grand Manor Court,4.142730,12.617306,6637.0,2.439786,25.798858,2.795201,72.194773
Highland View,4.146351,13.327529,6643.0,5.319748,14.559941,2.771704,40.434617
Highway Plaza,4.043679,12.728674,6621.0,4.466084,14.935427,2.764774,41.312348
Industrial Station,3.842015,13.129804,6639.0,3.389411,6.485115,2.745218,17.813211
Kennedy Station,4.197640,13.007866,6650.0,2.502458,17.649882,2.755103,48.669853
Legacy Way,4.128655,12.858918,6648.0,6.061404,14.533962,2.746316,39.833465
Lester Avenue,4.140139,13.406497,6640.0,4.445476,11.457703,2.753972,31.529318
Lexington Drive,4.068540,14.256410,6602.0,8.109961,17.507411,2.765843,48.473185
Liberty Square,3.858476,13.728616,6651.0,3.360031,16.648966,2.788911,46.477970
Marshall Drive,4.183089,13.729028,6631.0,6.177097,14.976245,2.786771,41.726052
Melrose Place,3.630384,13.581490,6620.0,7.596624,11.079930,2.775797,30.682841
Nevada Park,4.185342,11.604651,6649.0,2.494010,18.800352,2.774785,52.175356
Norway Market,4.149511,13.476945,6628.0,4.518398,15.003968,2.755622,41.385128
Oakland Road,4.148474,13.713432,6604.0,6.327461,18.210047,2.745999,50.088163
Pine Valley,4.158944,12.933724,6646.0,3.476833,9.494018,2.745472,26.000205
Quincy Drive,4.072176,13.497908,6618.0,4.573745,11.754095,2.786124,32.778033
Reagan Street,4.156668,13.588994,6617.0,4.459098,7.653480,2.734983,20.916663
Red Oak,4.158064,13.039953,6644.0,6.365996,19.911668,2.766188,55.199939
Sycamore Avenue,4.147898,12.745288,6636.0,4.582407,16.115771,2.737385,44.267535
Texas Market,4.191331,13.233800,6609.0,4.460158,20.202982,2.744365,55.327360
Union Square,4.049003,12.846724,6642.0,4.334473,10.841630,2.797009,30.413504
Veteran Square,3.695884,13.018293,6638.0,4.045732,15.441303,2.772660,42.906082